# GET http://localhost:3001/api/notes

GET http://localhost:3001/api/notes/696ce8fb3f813799275f5c2a

###
POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content": "lol",
    "important": true
}
###
DELETE http://localhost:3001/api/notes/696e2d2a96bb17978294a012
